title: Elinbhu
description: My Personal Blog
author: victor 
logo: http://aboutashu.com/hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/elinbhu
about: free developer
disqus_shortname: 
google_analytics: 
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Resume
      url: '#'
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/elinbhu
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
      
social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-skype
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'
    - icon: fa-stack-exchange
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://elinbhu.github.io/"
baseurl: "/"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
